### PR TITLE
Fix timestamp keys for Zabbix sender request (backport #22 to v0.12)

### PR DESCRIPTION
**Pull request by wktk**
Due to some reasons, I'm currently running fluentd v0.12 also. While I acknowledge that v0.12 may be deemed outdated, I would be grateful if we could consider a backport to the fluentd-v0.12 branch...!

### CODE REVIEW

**Comment by fujiwara** [comment]
@wktk Thank you!
Would you need to release the new version v0.2.4 based on fluentd-v0.12 branch?

**Comment by wktk** [comment]
Thank you, I'd appreciate it if you could, but no worries if it's not possible!

**Comment by fujiwara** [comment]
https://rubygems.org/gems/fluent-plugin-zabbix/versions/0.2.4 released!

(I'm sorry I didn't test this version in natural environments with Fluentd v0.12.)

**Comment by wktk** [comment]
Thank you for taking the time for this. I'm grateful for your kindness!

**Pull request merged**
